### ISSUE TITLE
Add notes about virtual environment/pip to README

### ISSUE THREAD

**Issue by bbradelTT** [tenstorrent/tt-flash#10]
https://github.com/tenstorrent/tt-flash/blob/main/README.md is confusing in that "Virtual environment" is marked as optional, while the pip commands will not work by default when following https://github.com/tenstorrent-metal/metal-internal-workflows/wiki/Creating-a-virtual-machine-on-the-TT-Cloud

Therefore, it would be good to note that if pip isn't installed, you can set up the Virtual environment (with a reference to earlier), which has pip. It would be good to have that note both in the non-development and development sections, either immediately before or after the first pip command in each section.

**Comment by warthog9** [comment]
I think this leans in the direction of being the wrong place for that?

Docs in this repo, particularly [tt-flash/README.md](tt-flash/README.md) has a base assumption of being developer centric documentation, not end user centric documentation.  I'd generally expect a developer to be able to work around pip being present/not present independently, the gotcha is that we are using python/pip to build rust packages thus the slight abnormality of those extra pieces of the docs.

If an end user shouldn't be ending up here, they should be going here: https://docs.tenstorrent.com/tenstorrent/add-in-boards-and-cooling-kits/grayskull-tm-e75-e150/software-setup, and maybe we need a clearer statement at the top of the README.md concerning that.

Since the metal repo noted doesn't seem to link here anymore anyway going to close this
